[package]
name = "rusty_chip8"
version = "0.1.0"
edition = "2021"

[lib]
name = "chip8_lib"
path = "src/chip8_lib/lib.rs"

[[bin]]
name = "chip8_frontend"
path = "src/chip8_frontend/bin.rs"

[dependencies]
ggez = "0.9.3"
thiserror = "1.0.64"
rand = "0.8.5"