name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-SDL2
          
      - name: Find pkg-config path
        shell: msys2 {0}
        run:
          pacboy -Fl pkg-config
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
