name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
      - name: Install dependencies
        with:
          update: true
          install: >-
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-SDL2
      - name: Find pkg-config path
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
      - shell: msys2 {0}
        run:
          pacman -Fl mingw-w64-x86_64-pkg-config
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
